site_name: 'python-backstage-79'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/romario-io/python-backstage-79
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
